### ISSUE TITLE
A new and more advanced implement of non-pollution DNS

### ISSUE THREAD

**Issue by hguandl** [SUSTC/issues#4]
[EDNS](https://en.wikipedia.org/wiki/Extension_mechanisms_for_DNS) is an enhanced domain name system. The advantages of using [Google DNS](https://developers.google.com/speed/public-dns) over EDNS are as follows:

* The current method that the GFW uses to pollute a DNS cannot affect the protocol of EDNS. Therefore, Google EDNS can be accessed without any proxy.

* Google DNS has a feature called [EDNS Client Subnet](https://developers.google.com/speed/public-dns/docs/ecs). We can send a request with the client IP and Google DNS will return the results which fit the IP's location best.

I've found a DNS server implement which supports EDNS. It is maintained by [lrinQVQ](https://github.com/lrinQVQ) and the source code can be downloaded [here](https://github.com/lrinQVQ/openwrt-chinadns/releases/download/v2.0.0/ChinaDNS-2.0.0.tar.gz). I think it would be a good alternative plan.

**Comment by lightsing** [comment]
already supported.
