### ISSUE TITLE
近来源同步很慢

### ISSUE THREAD

**Issue by JiangXL** [SUSTC/issues#6]
发现现在 Arch Linux 的源还是 1.2 的，其他镜像同步也很慢。
请问发生了什么。。。

**Comment by lightsing** [comment]
学校现在限速，出口带宽不够

**Comment by JiangXL** [comment]
好吧 : (

在 2018年1月11日，15:44，HHQ. Zhang <notifications@github.com<mailto:notifications@github.com>> 写道：


学校现在限速，出口带宽不够
