### ISSUE TITLE
请考虑增加openwrt和Raspbian的镜像。

### ISSUE THREAD

**Issue by sparkcyf** [SUSTC/issues#8]
**openwrt**和**rpi**亦或是类似的开发板在校内应该还是有一些保有量的，但由于众所周知的原因这些硬件的软件源的下载都十分缓慢。

**openwrt** 上游 USTCMiror
https://lug.ustc.edu.cn/wiki/mirrors/help/openwrt
**rpi** 上游 Tsinghua TUNA
https://mirror.tuna.tsinghua.edu.cn/help/raspbian/

  我不太清楚在此处开issue是否妥当。如有误，请见谅。

**Comment by lightsing** [comment]
镜像站迁移至新机器后会逐步增加镜像，还请暂时使用友校的镜像

**Comment by sparkcyf** [comment]
Done in https://mirrors.sustech.edu.cn/raspberrypi/ and https://mirrors.sustech.edu.cn/raspbian/ .
